// Mocks generated by Mockito 5.4.4 from annotations
// in talia_quran/test/features/home/presentation/cubits/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i19;
import 'package:talia_quran/core/error/app_failure.dart' as _i6;
import 'package:talia_quran/core/memorization/memorization_path_resolver.dart'
    as _i16;
import 'package:talia_quran/core/memorization/smart_coach_recommendation.dart'
    as _i18;
import 'package:talia_quran/core/memorization/usecases/get_smart_coach_recommendation_usecase.dart'
    as _i17;
import 'package:talia_quran/core/services/app_session_service.dart' as _i15;
import 'package:talia_quran/features/hifz/domain/entities/hifz_entities.dart'
    as _i9;
import 'package:talia_quran/features/hifz/domain/usecases/get_hifz_progress_usecase.dart'
    as _i8;
import 'package:talia_quran/features/home/domain/usecases/get_activity_heatmap_usecase.dart'
    as _i3;
import 'package:talia_quran/features/memorization_plus/domain/entities/memorization_entities.dart'
    as _i13;
import 'package:talia_quran/features/memorization_plus/domain/repositories/memorization_plus_repository.dart'
    as _i14;
import 'package:talia_quran/features/memorization_plus/domain/usecases/memorization_plus_usecases.dart'
    as _i12;
import 'package:talia_quran/features/progress/domain/entities/progress_entities.dart'
    as _i7;
import 'package:talia_quran/features/progress/domain/usecases/get_progress_usecase.dart'
    as _i4;
import 'package:talia_quran/features/quran/domain/entities/quran_entities.dart'
    as _i11;
import 'package:talia_quran/features/quran/domain/usecases/get_surahs_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityHeatmapData_1 extends _i1.SmartFake
    implements _i3.ActivityHeatmapData {
  _FakeActivityHeatmapData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProgressUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProgressUsecase extends _i1.Mock
    implements _i4.GetProgressUsecase {
  MockGetProgressUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.OverallProgress>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.OverallProgress>>.value(
                _FakeEither_0<_i6.Failure, _i7.OverallProgress>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.OverallProgress>>);
}

/// A class which mocks [GetHifzProgressUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHifzProgressUsecase extends _i1.Mock
    implements _i8.GetHifzProgressUsecase {
  MockGetHifzProgressUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i9.SurahHifzProgress>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, List<_i9.SurahHifzProgress>>>.value(
            _FakeEither_0<_i6.Failure, List<_i9.SurahHifzProgress>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i9.SurahHifzProgress>>>);
}

/// A class which mocks [GetQuranPageUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuranPageUsecase extends _i1.Mock
    implements _i10.GetQuranPageUsecase {
  MockGetQuranPageUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i11.QuranPageDetail>> call(
          int? pageNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [pageNumber],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i11.QuranPageDetail>>.value(
                _FakeEither_0<_i6.Failure, _i11.QuranPageDetail>(
          this,
          Invocation.method(
            #call,
            [pageNumber],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i11.QuranPageDetail>>);
}

/// A class which mocks [GetCustomPlanUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCustomPlanUsecase extends _i1.Mock
    implements _i12.GetCustomPlanUsecase {
  MockGetCustomPlanUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.CustomMemorizationPlan?>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i6.Failure, _i13.CustomMemorizationPlan?>>.value(
            _FakeEither_0<_i6.Failure, _i13.CustomMemorizationPlan?>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.CustomMemorizationPlan?>>);
}

/// A class which mocks [MemorizationPlusRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemorizationPlusRepository extends _i1.Mock
    implements _i14.MemorizationPlusRepository {
  MockMemorizationPlusRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>
      getMemorizationProfile() => (super.noSuchMethod(
            Invocation.method(
              #getMemorizationProfile,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
              this,
              Invocation.method(
                #getMemorizationProfile,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, _i13.MemorizationProfile>> selectMemorizationPath(
          _i13.MemorizationPath? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectMemorizationPath,
          [path],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
          this,
          Invocation.method(
            #selectMemorizationPath,
            [path],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>
      continueWithoutGuardian() => (super.noSuchMethod(
            Invocation.method(
              #continueWithoutGuardian,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
              this,
              Invocation.method(
                #continueWithoutGuardian,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.PairingSession>>
      createGuardianPairingSession() => (super.noSuchMethod(
            Invocation.method(
              #createGuardianPairingSession,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i13.PairingSession>>.value(
                    _FakeEither_0<_i6.Failure, _i13.PairingSession>(
              this,
              Invocation.method(
                #createGuardianPairingSession,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.PairingSession>>);

  @override
  _i5.Future<
      _i2
      .Either<_i6.Failure, _i13.MemorizationProfile>> acceptGuardianPairingCode(
          String? codeOrQrData) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptGuardianPairingCode,
          [codeOrQrData],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
          this,
          Invocation.method(
            #acceptGuardianPairingCode,
            [codeOrQrData],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.PairingSession?>>
      refreshPairingSession() => (super.noSuchMethod(
            Invocation.method(
              #refreshPairingSession,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i13.PairingSession?>>.value(
                    _FakeEither_0<_i6.Failure, _i13.PairingSession?>(
              this,
              Invocation.method(
                #refreshPairingSession,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.PairingSession?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>
      unlinkGuardian() => (super.noSuchMethod(
            Invocation.method(
              #unlinkGuardian,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
              this,
              Invocation.method(
                #unlinkGuardian,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, _i13.MemorizationProfile>> setParentGuardianMode(
          bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setParentGuardianMode,
          [value],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
          this,
          Invocation.method(
            #setParentGuardianMode,
            [value],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>
      refreshChildGuardianLink() => (super.noSuchMethod(
            Invocation.method(
              #refreshChildGuardianLink,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
              this,
              Invocation.method(
                #refreshChildGuardianLink,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>
      resetMemorizationIdentity() => (super.noSuchMethod(
            Invocation.method(
              #resetMemorizationIdentity,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i13.MemorizationProfile>>.value(
                _FakeEither_0<_i6.Failure, _i13.MemorizationProfile>(
              this,
              Invocation.method(
                #resetMemorizationIdentity,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.MemorizationProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.SmartMemorizationSettings>>
      getSmartSettings() => (super.noSuchMethod(
            Invocation.method(
              #getSmartSettings,
              [],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, _i13.SmartMemorizationSettings>>.value(
                _FakeEither_0<_i6.Failure, _i13.SmartMemorizationSettings>(
              this,
              Invocation.method(
                #getSmartSettings,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, _i13.SmartMemorizationSettings>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveSmartSettings(
          _i13.SmartMemorizationSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSmartSettings,
          [settings],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveSmartSettings,
            [settings],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i2.Either<_i6.Failure, _i13.MemorizationTrack?> getSelectedTrack() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedTrack,
          [],
        ),
        returnValue: _FakeEither_0<_i6.Failure, _i13.MemorizationTrack?>(
          this,
          Invocation.method(
            #getSelectedTrack,
            [],
          ),
        ),
      ) as _i2.Either<_i6.Failure, _i13.MemorizationTrack?>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveSelectedTrack(
          _i13.MemorizationTrack? track) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedTrack,
          [track],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveSelectedTrack,
            [track],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.DailyPlan>> generateDailyPlan({
    required int? surahId,
    required int? newAyahsPerDay,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateDailyPlan,
          [],
          {
            #surahId: surahId,
            #newAyahsPerDay: newAyahsPerDay,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, _i13.DailyPlan>>.value(
            _FakeEither_0<_i6.Failure, _i13.DailyPlan>(
          this,
          Invocation.method(
            #generateDailyPlan,
            [],
            {
              #surahId: surahId,
              #newAyahsPerDay: newAyahsPerDay,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.DailyPlan>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.DailyPlan?>> getCachedDailyPlan() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDailyPlan,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, _i13.DailyPlan?>>.value(
            _FakeEither_0<_i6.Failure, _i13.DailyPlan?>(
          this,
          Invocation.method(
            #getCachedDailyPlan,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.DailyPlan?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveDailyPlan(
          _i13.DailyPlan? plan) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDailyPlan,
          [plan],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveDailyPlan,
            [plan],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord?>> getReviewRecord(
    int? surahId,
    int? ayahNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewRecord,
          [
            surahId,
            ayahNumber,
          ],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord?>>.value(
                _FakeEither_0<_i6.Failure, _i13.AyahReviewRecord?>(
          this,
          Invocation.method(
            #getReviewRecord,
            [
              surahId,
              ayahNumber,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.AyahReviewRecord>>>
      getAllReviewRecords() => (super.noSuchMethod(
            Invocation.method(
              #getAllReviewRecords,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, List<_i13.AyahReviewRecord>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.AyahReviewRecord>>(
              this,
              Invocation.method(
                #getAllReviewRecords,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, List<_i13.AyahReviewRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveReviewRecord(
          _i13.AyahReviewRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReviewRecord,
          [record],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveReviewRecord,
            [record],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord>> evaluateAyah({
    required int? surahId,
    required int? ayahNumber,
    required _i13.PerformanceRating? rating,
    _i13.ReviewRecordCreatedByMode? createdByMode =
        _i13.ReviewRecordCreatedByMode.adultMemPlus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evaluateAyah,
          [],
          {
            #surahId: surahId,
            #ayahNumber: ayahNumber,
            #rating: rating,
            #createdByMode: createdByMode,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord>>.value(
                _FakeEither_0<_i6.Failure, _i13.AyahReviewRecord>(
          this,
          Invocation.method(
            #evaluateAyah,
            [],
            {
              #surahId: surahId,
              #ayahNumber: ayahNumber,
              #rating: rating,
              #createdByMode: createdByMode,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord>> markAyahMemorized({
    required int? surahId,
    required int? ayahNumber,
    _i13.ReviewRecordCreatedByMode? createdByMode =
        _i13.ReviewRecordCreatedByMode.kidsMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAyahMemorized,
          [],
          {
            #surahId: surahId,
            #ayahNumber: ayahNumber,
            #createdByMode: createdByMode,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord>>.value(
                _FakeEither_0<_i6.Failure, _i13.AyahReviewRecord>(
          this,
          Invocation.method(
            #markAyahMemorized,
            [],
            {
              #surahId: surahId,
              #ayahNumber: ayahNumber,
              #createdByMode: createdByMode,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.AyahReviewRecord>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.KidsProgress>> getKidsProgress() =>
      (super.noSuchMethod(
        Invocation.method(
          #getKidsProgress,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.KidsProgress>>.value(
                _FakeEither_0<_i6.Failure, _i13.KidsProgress>(
          this,
          Invocation.method(
            #getKidsProgress,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.KidsProgress>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveKidsProgress(
          _i13.KidsProgress? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKidsProgress,
          [progress],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveKidsProgress,
            [progress],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, List<_i13.KidsJourneyStage>>> getKidsJourney(
          {required int? surahId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKidsJourney,
          [],
          {#surahId: surahId},
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, List<_i13.KidsJourneyStage>>>.value(
            _FakeEither_0<_i6.Failure, List<_i13.KidsJourneyStage>>(
          this,
          Invocation.method(
            #getKidsJourney,
            [],
            {#surahId: surahId},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i13.KidsJourneyStage>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.KidsSessionLog>>>
      getKidsSessionLogs() => (super.noSuchMethod(
            Invocation.method(
              #getKidsSessionLogs,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, List<_i13.KidsSessionLog>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.KidsSessionLog>>(
              this,
              Invocation.method(
                #getKidsSessionLogs,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i13.KidsSessionLog>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.KidsSessionLog>> saveKidsSessionLog({
    required int? surahId,
    required int? ayahNumber,
    required int? repeatsCompleted,
    required int? pointsEarned,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKidsSessionLog,
          [],
          {
            #surahId: surahId,
            #ayahNumber: ayahNumber,
            #repeatsCompleted: repeatsCompleted,
            #pointsEarned: pointsEarned,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.KidsSessionLog>>.value(
                _FakeEither_0<_i6.Failure, _i13.KidsSessionLog>(
          this,
          Invocation.method(
            #saveKidsSessionLog,
            [],
            {
              #surahId: surahId,
              #ayahNumber: ayahNumber,
              #repeatsCompleted: repeatsCompleted,
              #pointsEarned: pointsEarned,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.KidsSessionLog>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.ParentDashboard>> getParentDashboard(
          {required int? surahId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParentDashboard,
          [],
          {#surahId: surahId},
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i13.ParentDashboard>>.value(
                _FakeEither_0<_i6.Failure, _i13.ParentDashboard>(
          this,
          Invocation.method(
            #getParentDashboard,
            [],
            {#surahId: surahId},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i13.ParentDashboard>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.ParentSettings>>
      getParentSettings() => (super.noSuchMethod(
            Invocation.method(
              #getParentSettings,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i13.ParentSettings>>.value(
                    _FakeEither_0<_i6.Failure, _i13.ParentSettings>(
              this,
              Invocation.method(
                #getParentSettings,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.ParentSettings>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveParentSettings(
          _i13.ParentSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveParentSettings,
          [settings],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveParentSettings,
            [settings],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, bool>> verifyParentPin(String? pin) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyParentPin,
          [pin],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #verifyParentPin,
            [pin],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> setParentPin(String? pin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setParentPin,
          [pin],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #setParentPin,
            [pin],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> resetParentAccess() =>
      (super.noSuchMethod(
        Invocation.method(
          #resetParentAccess,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #resetParentAccess,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>> saveParentReward(
          String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveParentReward,
          [title],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.ParentReward>>(
          this,
          Invocation.method(
            #saveParentReward,
            [title],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>
      claimParentReward(String? id) => (super.noSuchMethod(
            Invocation.method(
              #claimParentReward,
              [id],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.ParentReward>>(
              this,
              Invocation.method(
                #claimParentReward,
                [id],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> createChildLinkToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #createChildLinkToken,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #createChildLinkToken,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> acceptChildLinkToken(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptChildLinkToken,
          [token],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #acceptChildLinkToken,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> syncKidsProgressToCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncKidsProgressToCloud,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #syncKidsProgressToCloud,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.RemoteChildSummary>>>
      getRemoteChildren() => (super.noSuchMethod(
            Invocation.method(
              #getRemoteChildren,
              [],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, List<_i13.RemoteChildSummary>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.RemoteChildSummary>>(
              this,
              Invocation.method(
                #getRemoteChildren,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, List<_i13.RemoteChildSummary>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>
      saveRemoteParentReward({
    required String? childUserId,
    required String? title,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #saveRemoteParentReward,
              [],
              {
                #childUserId: childUserId,
                #title: title,
              },
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.ParentReward>>(
              this,
              Invocation.method(
                #saveRemoteParentReward,
                [],
                {
                  #childUserId: childUserId,
                  #title: title,
                },
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i13.ParentReward>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.KidsCompletionResult>>
      awardKidsPoints({
    required int? surahId,
    required int? ayahNumber,
    required int? repeatsCompleted,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #awardKidsPoints,
              [],
              {
                #surahId: surahId,
                #ayahNumber: ayahNumber,
                #repeatsCompleted: repeatsCompleted,
              },
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i13.KidsCompletionResult>>.value(
                _FakeEither_0<_i6.Failure, _i13.KidsCompletionResult>(
              this,
              Invocation.method(
                #awardKidsPoints,
                [],
                {
                  #surahId: surahId,
                  #ayahNumber: ayahNumber,
                  #repeatsCompleted: repeatsCompleted,
                },
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i13.KidsCompletionResult>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.CustomMemorizationPlan?>>
      getCustomPlan() => (super.noSuchMethod(
            Invocation.method(
              #getCustomPlan,
              [],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, _i13.CustomMemorizationPlan?>>.value(
                _FakeEither_0<_i6.Failure, _i13.CustomMemorizationPlan?>(
              this,
              Invocation.method(
                #getCustomPlan,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, _i13.CustomMemorizationPlan?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveCustomPlan(
          _i13.CustomMemorizationPlan? plan) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomPlan,
          [plan],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveCustomPlan,
            [plan],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteCustomPlan() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomPlan,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteCustomPlan,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i2.Either<_i6.Failure, bool> getIsParentMode() => (super.noSuchMethod(
        Invocation.method(
          #getIsParentMode,
          [],
        ),
        returnValue: _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #getIsParentMode,
            [],
          ),
        ),
      ) as _i2.Either<_i6.Failure, bool>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> setIsParentMode(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIsParentMode,
          [value],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #setIsParentMode,
            [value],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [AppSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSessionService extends _i1.Mock implements _i15.AppSessionService {
  MockAppSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveLocation(String? location) => (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [location],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearLastRestorableLocation() => (super.noSuchMethod(
        Invocation.method(
          #clearLastRestorableLocation,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GetActivityHeatmapUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActivityHeatmapUsecase extends _i1.Mock
    implements _i3.GetActivityHeatmapUsecase {
  MockGetActivityHeatmapUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ActivityHeatmapData> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.ActivityHeatmapData>.value(
            _FakeActivityHeatmapData_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ActivityHeatmapData>);
}

/// A class which mocks [MemorizationPathResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemorizationPathResolver extends _i1.Mock
    implements _i16.MemorizationPathResolver {
  MockMemorizationPathResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<void> get changes => (super.noSuchMethod(
        Invocation.getter(#changes),
        returnValue: _i5.Stream<void>.empty(),
      ) as _i5.Stream<void>);

  @override
  _i5.Future<_i13.MemorizationProfile?> currentProfile() => (super.noSuchMethod(
        Invocation.method(
          #currentProfile,
          [],
        ),
        returnValue: _i5.Future<_i13.MemorizationProfile?>.value(),
      ) as _i5.Future<_i13.MemorizationProfile?>);

  @override
  bool isKids(_i13.MemorizationProfile? profile) => (super.noSuchMethod(
        Invocation.method(
          #isKids,
          [profile],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isAdult(_i13.MemorizationProfile? profile) => (super.noSuchMethod(
        Invocation.method(
          #isAdult,
          [profile],
        ),
        returnValue: false,
      ) as bool);

  @override
  void notifyChanged() => super.noSuchMethod(
        Invocation.method(
          #notifyChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GetSmartCoachRecommendationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSmartCoachRecommendationUsecase extends _i1.Mock
    implements _i17.GetSmartCoachRecommendationUsecase {
  MockGetSmartCoachRecommendationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i18.SmartCoachRecommendation?>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i6.Failure, _i18.SmartCoachRecommendation?>>.value(
            _FakeEither_0<_i6.Failure, _i18.SmartCoachRecommendation?>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i18.SmartCoachRecommendation?>>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i19.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i5.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
