param([int]$Start=1,[int]$End=1)
$ErrorActionPreference='Stop'; $root=$PSScriptRoot; $parent=Split-Path $root; $plan=Get-Content "$parent/campaign-plan.json" -Raw|ConvertFrom-Json; $assets=@(Get-Content "$parent/superdesign-assets.json" -Raw|ConvertFrom-Json); $font=(Get-Content "$root/font-asset.json" -Raw|ConvertFrom-Json).url
$assets += [pscustomobject]@{name='04-reader-clean';asset=[pscustomobject]@{nodeId='63e0a8b4-9d47-4997-9120-e247b3445308';url='https://vgbujcuwptvheqijyjbe.supabase.co/storage/v1/object/public/hmac-uploads/projects/1e8d0a36-f2e3-4302-b966-9a9a009d58e9/content-assets/2866b701e660781d85b20661e3b6c833bbaf395805c5a429eea63820821892fc/04-reader-clean.png'}}
$base=if($Start -eq 1){'50633c49-4269-41dc-8748-afad0b096ab6'}else{(Get-Content "$root/designs/01-draft.json" -Raw|ConvertFrom-Json).draftId}
$argsList=@('--yes','@superdesign/cli@latest','iterate-design-draft','--draft-id',$base,'--mode','branch','--device','custom','--width','1080','--height','1920','--user-request','استخدم نفس الصور مرة اخري ولكن بتصميم والوان ورؤيه مختلفة','--json'); $refs=@('talia-official-logo')
foreach($s in $plan.slides|Where-Object {$_.id -ge $Start -and $_.id -le $End}){$a=($assets|Where-Object name -eq $s.source).asset; $head=$s.headline.Replace("`n",' / '); $pal=if($s.id%3 -eq 1){'cobalt #3048CF background, white headline, peach #FFC7AA large disk, lilac accents'}elseif($s.id%3 -eq 2){'pale lavender #EEE9FF background, ink #222548 text, bright coral #FA7B60 and cobalt accents'}else{'soft peach #FFE3D1 background, ink #222548 text, cobalt block and white accents'}; $layout=if($s.id%4 -eq 0){'screenshot centered x190 y180 width700 height1245; headline below at y1460 and support y1760; logo top60'}else{'headline centered y170 in 2 lines; support y425; screenshot offset RIGHT x290 y590 width700 height1245; left margin has large chapter number and small category text; logo top60'};
$p="DIRECTION 02 poster $($s.id): completely new contemporary editorial family campaign. $pal. Flat oversized geometric disks, broad color blocks, subtle paper grain, confident negative space. No arches, gold ornament, gradients or old Reem Kufi font. Layout: $layout. Arabic Noto Naskh bold headline90px, support36px via @font-face $font. EXACT headline: $head. EXACT support: $($s.support). Small category: $($s.screen). Exact screenshot img: $($a.url). Preserve img original pixels and ratio, entire image visible, no transforms/tilt/crops/overlays on screenshot; image may have32px corners, thin white border, subtle offset shadow. Original logo as supplied. Editable HTML text, fixed1080x1920, all content within60px safe margins. No fabricated Quran or UI. Keep decorative disks away from headline/support to preserve contrast. No footer metadata or copyright/year text. Use actual @font-face, never @import of ttf. Style must be visibly different from green first collection, coordinated with other direction02 posters."; $argsList+=@('-p',$p); $refs+=$a.nodeId}
$argsList+=@('--reference-id')+$refs; $out=& npx @argsList; if($LASTEXITCODE -ne 0){throw 'Generation failed'}; $out|Set-Content "$root/designs/batch-$Start-$End.json" -Encoding utf8; $batch=$out|ConvertFrom-Json
foreach($d in $batch.drafts){$json=& npx --yes @superdesign/cli@latest get-design --draft-id $d.draftId --json; if($LASTEXITCODE -ne 0){throw 'Read failed'}; $v=$json|ConvertFrom-Json; $match=@($plan.slides|Where-Object {$v.htmlContent.Contains($_.source+'.png')}); if($match.Count -ne 1){throw 'Ambiguous screenshot'}; $id=$match[0].id.ToString('00'); $json|Set-Content "$root/designs/$id-draft.json" -Encoding utf8; $v.htmlContent|Set-Content "$root/designs/$id.html" -Encoding utf8; Write-Output "$id saved $($d.draftId)"}

