// Mocks generated by Mockito 5.4.4 from annotations
// in talia_quran/test/features/auth/auth_cubit_lifecycle_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talia_quran/core/error/app_failure.dart' as _i6;
import 'package:talia_quran/features/auth/domain/entities/app_user.dart' as _i5;
import 'package:talia_quran/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AppUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i5.AppUser?>.empty(),
      ) as _i4.Stream<_i5.AppUser?>);

  @override
  _i4.Stream<void> get passwordRecoveryChanges => (super.noSuchMethod(
        Invocation.getter(#passwordRecoveryChanges),
        returnValue: _i4.Stream<void>.empty(),
      ) as _i4.Stream<void>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.AppUser>> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.AppUser>>.value(
            _FakeEither_0<_i6.Failure, _i5.AppUser>(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.AppUser>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.AppUser>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.AppUser>>.value(
            _FakeEither_0<_i6.Failure, _i5.AppUser>(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.AppUser>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> signOut() =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> syncProgressToCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncProgressToCloud,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #syncProgressToCloud,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> pullProgressFromCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #pullProgressFromCloud,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #pullProgressFromCloud,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<bool> hasPendingCloudPush() =>
      (super.noSuchMethod(
        Invocation.method(
          #hasPendingCloudPush,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);


  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> resendConfirmation(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendConfirmation,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendConfirmation,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> resetPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resetPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> updatePassword(
          String? newPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i6.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #updatePassword,
            [newPassword],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
}
