// GENERATED by tools/icons/build_talia_icons.py. Do not edit by hand:
// change the SVG sources or manifest.json and rebuild.

import 'package:flutter/widgets.dart';

/// The Talia icon set: one monoline language (1.75 stroke on a 24 grid,
/// round caps) with the gold nuqta marking Talia feature icons.
///
/// Use these everywhere instead of Material `Icons`. Render through
/// `TaliaIcon` to get the gold nuqta on active icons and the kids variant
/// inside a `TaliaIconScope.kids` subtree.
abstract final class TaliaIcons {
  static const IconData home = IconData(0xe000, fontFamily: 'TaliaIcons');
  static const IconData mushaf = IconData(0xe001, fontFamily: 'TaliaIcons');
  static const IconData reading = IconData(0xe002, fontFamily: 'TaliaIcons');
  static const IconData hifz = IconData(0xe003, fontFamily: 'TaliaIcons');
  static const IconData recite = IconData(0xe004, fontFamily: 'TaliaIcons');
  static const IconData mic = IconData(0xe005, fontFamily: 'TaliaIcons');
  static const IconData azkar = IconData(0xe006, fontFamily: 'TaliaIcons');
  static const IconData dua = IconData(0xe007, fontFamily: 'TaliaIcons');
  static const IconData prayer = IconData(0xe008, fontFamily: 'TaliaIcons');
  static const IconData flame = IconData(0xe009, fontFamily: 'TaliaIcons');
  static const IconData medal = IconData(0xe00a, fontFamily: 'TaliaIcons');
  static const IconData certificate = IconData(
    0xe00b,
    fontFamily: 'TaliaIcons',
  );
  static const IconData trophy = IconData(0xe00c, fontFamily: 'TaliaIcons');
  static const IconData progress = IconData(
    0xe00d,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData sparkle = IconData(0xe00e, fontFamily: 'TaliaIcons');
  static const IconData journey = IconData(0xe00f, fontFamily: 'TaliaIcons');
  static const IconData listen = IconData(0xe010, fontFamily: 'TaliaIcons');
  static const IconData family = IconData(0xe011, fontFamily: 'TaliaIcons');
  static const IconData child = IconData(0xe012, fontFamily: 'TaliaIcons');
  static const IconData people = IconData(0xe013, fontFamily: 'TaliaIcons');
  static const IconData person = IconData(0xe014, fontFamily: 'TaliaIcons');
  static const IconData guardian = IconData(0xe015, fontFamily: 'TaliaIcons');
  static const IconData shield = IconData(0xe016, fontFamily: 'TaliaIcons');
  static const IconData shieldCheck = IconData(
    0xe017,
    fontFamily: 'TaliaIcons',
  );
  static const IconData verified = IconData(0xe018, fontFamily: 'TaliaIcons');
  static const IconData library = IconData(0xe019, fontFamily: 'TaliaIcons');
  static const IconData readerMode = IconData(
    0xe01a,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData waveform = IconData(0xe01b, fontFamily: 'TaliaIcons');
  static const IconData sun = IconData(0xe01c, fontFamily: 'TaliaIcons');
  static const IconData moon = IconData(0xe01d, fontFamily: 'TaliaIcons');
  static const IconData sunrise = IconData(0xe01e, fontFamily: 'TaliaIcons');
  static const IconData cloudSun = IconData(0xe01f, fontFamily: 'TaliaIcons');
  static const IconData themeAuto = IconData(0xe020, fontFamily: 'TaliaIcons');
  static const IconData contrast = IconData(0xe021, fontFamily: 'TaliaIcons');
  static const IconData flag = IconData(0xe022, fontFamily: 'TaliaIcons');
  static const IconData school = IconData(0xe023, fontFamily: 'TaliaIcons');
  static const IconData idea = IconData(0xe024, fontFamily: 'TaliaIcons');
  static const IconData bolt = IconData(0xe025, fontFamily: 'TaliaIcons');
  static const IconData rocket = IconData(0xe026, fontFamily: 'TaliaIcons');
  static const IconData celebrate = IconData(0xe027, fontFamily: 'TaliaIcons');
  static const IconData gift = IconData(0xe028, fontFamily: 'TaliaIcons');
  static const IconData gem = IconData(0xe029, fontFamily: 'TaliaIcons');
  static const IconData wave = IconData(0xe02a, fontFamily: 'TaliaIcons');
  static const IconData smile = IconData(0xe02b, fontFamily: 'TaliaIcons');
  static const IconData meh = IconData(0xe02c, fontFamily: 'TaliaIcons');
  static const IconData frown = IconData(0xe02d, fontFamily: 'TaliaIcons');
  static const IconData tree = IconData(0xe02e, fontFamily: 'TaliaIcons');
  static const IconData flower = IconData(0xe02f, fontFamily: 'TaliaIcons');
  static const IconData mountain = IconData(0xe030, fontFamily: 'TaliaIcons');
  static const IconData water = IconData(0xe031, fontFamily: 'TaliaIcons');
  static const IconData heal = IconData(0xe032, fontFamily: 'TaliaIcons');
  static const IconData hub = IconData(0xe033, fontFamily: 'TaliaIcons');
  static const IconData balance = IconData(0xe034, fontFamily: 'TaliaIcons');
  static const IconData chart = IconData(0xe035, fontFamily: 'TaliaIcons');
  static const IconData trendingDown = IconData(
    0xe036,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData tap = IconData(0xe037, fontFamily: 'TaliaIcons');
  static const IconData translate = IconData(0xe038, fontFamily: 'TaliaIcons');
  static const IconData quote = IconData(0xe039, fontFamily: 'TaliaIcons');
  static const IconData star = IconData(0xe03a, fontFamily: 'TaliaIcons');
  static const IconData starFilled = IconData(0xe03b, fontFamily: 'TaliaIcons');
  static const IconData starHalf = IconData(
    0xe03c,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData bookmark = IconData(0xe03d, fontFamily: 'TaliaIcons');
  static const IconData bookmarkFilled = IconData(
    0xe03e,
    fontFamily: 'TaliaIcons',
  );
  static const IconData bookmarkCheck = IconData(
    0xe03f,
    fontFamily: 'TaliaIcons',
  );
  static const IconData heartFilled = IconData(
    0xe040,
    fontFamily: 'TaliaIcons',
  );
  static const IconData circle = IconData(0xe041, fontFamily: 'TaliaIcons');
  static const IconData circleFilled = IconData(
    0xe042,
    fontFamily: 'TaliaIcons',
  );
  static const IconData target = IconData(0xe043, fontFamily: 'TaliaIcons');
  static const IconData checkCircle = IconData(
    0xe044,
    fontFamily: 'TaliaIcons',
  );
  static const IconData checkCircleFilled = IconData(
    0xe045,
    fontFamily: 'TaliaIcons',
  );
  static const IconData playCircle = IconData(0xe046, fontFamily: 'TaliaIcons');
  static const IconData playCircleFilled = IconData(
    0xe047,
    fontFamily: 'TaliaIcons',
  );
  static const IconData pauseCircle = IconData(
    0xe048,
    fontFamily: 'TaliaIcons',
  );
  static const IconData pauseCircleFilled = IconData(
    0xe049,
    fontFamily: 'TaliaIcons',
  );
  static const IconData stopCircle = IconData(0xe04a, fontFamily: 'TaliaIcons');
  static const IconData stopCircleFilled = IconData(
    0xe04b,
    fontFamily: 'TaliaIcons',
  );
  static const IconData play = IconData(0xe04c, fontFamily: 'TaliaIcons');
  static const IconData pause = IconData(0xe04d, fontFamily: 'TaliaIcons');
  static const IconData stop = IconData(0xe04e, fontFamily: 'TaliaIcons');
  static const IconData skipNext = IconData(0xe04f, fontFamily: 'TaliaIcons');
  static const IconData skipPrevious = IconData(
    0xe050,
    fontFamily: 'TaliaIcons',
  );
  static const IconData volume = IconData(0xe051, fontFamily: 'TaliaIcons');
  static const IconData volumeOff = IconData(0xe052, fontFamily: 'TaliaIcons');
  static const IconData repeat = IconData(0xe053, fontFamily: 'TaliaIcons');
  static const IconData shuffle = IconData(0xe054, fontFamily: 'TaliaIcons');
  static const IconData arrowBack = IconData(
    0xe055,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData arrowForward = IconData(
    0xe056,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData chevronBack = IconData(
    0xe057,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData chevronForward = IconData(
    0xe058,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData chevronDown = IconData(
    0xe059,
    fontFamily: 'TaliaIcons',
  );
  static const IconData firstPage = IconData(
    0xe05a,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData lastPage = IconData(
    0xe05b,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData swapVertical = IconData(
    0xe05c,
    fontFamily: 'TaliaIcons',
  );
  static const IconData swapHorizontal = IconData(
    0xe05d,
    fontFamily: 'TaliaIcons',
  );
  static const IconData externalLink = IconData(
    0xe05e,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData send = IconData(
    0xe05f,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData undo = IconData(
    0xe060,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData close = IconData(0xe061, fontFamily: 'TaliaIcons');
  static const IconData check = IconData(0xe062, fontFamily: 'TaliaIcons');
  static const IconData add = IconData(0xe063, fontFamily: 'TaliaIcons');
  static const IconData addCircle = IconData(0xe064, fontFamily: 'TaliaIcons');
  static const IconData addTask = IconData(0xe065, fontFamily: 'TaliaIcons');
  static const IconData refresh = IconData(0xe066, fontFamily: 'TaliaIcons');
  static const IconData replay = IconData(0xe067, fontFamily: 'TaliaIcons');
  static const IconData share = IconData(0xe068, fontFamily: 'TaliaIcons');
  static const IconData shareUp = IconData(0xe069, fontFamily: 'TaliaIcons');
  static const IconData copy = IconData(0xe06a, fontFamily: 'TaliaIcons');
  static const IconData edit = IconData(0xe06b, fontFamily: 'TaliaIcons');
  static const IconData delete = IconData(0xe06c, fontFamily: 'TaliaIcons');
  static const IconData deleteForever = IconData(
    0xe06d,
    fontFamily: 'TaliaIcons',
  );
  static const IconData search = IconData(0xe06e, fontFamily: 'TaliaIcons');
  static const IconData searchOff = IconData(0xe06f, fontFamily: 'TaliaIcons');
  static const IconData settings = IconData(0xe070, fontFamily: 'TaliaIcons');
  static const IconData settingsSmart = IconData(
    0xe071,
    fontFamily: 'TaliaIcons',
  );
  static const IconData tune = IconData(0xe072, fontFamily: 'TaliaIcons');
  static const IconData more = IconData(0xe073, fontFamily: 'TaliaIcons');
  static const IconData show = IconData(0xe074, fontFamily: 'TaliaIcons');
  static const IconData hide = IconData(0xe075, fontFamily: 'TaliaIcons');
  static const IconData lock = IconData(0xe076, fontFamily: 'TaliaIcons');
  static const IconData lockReset = IconData(0xe077, fontFamily: 'TaliaIcons');
  static const IconData key = IconData(0xe078, fontFamily: 'TaliaIcons');
  static const IconData info = IconData(0xe079, fontFamily: 'TaliaIcons');
  static const IconData error = IconData(0xe07a, fontFamily: 'TaliaIcons');
  static const IconData warning = IconData(0xe07b, fontFamily: 'TaliaIcons');
  static const IconData cloudOff = IconData(0xe07c, fontFamily: 'TaliaIcons');
  static const IconData cloudUpload = IconData(
    0xe07d,
    fontFamily: 'TaliaIcons',
  );
  static const IconData wifiOff = IconData(0xe07e, fontFamily: 'TaliaIcons');
  static const IconData download = IconData(0xe07f, fontFamily: 'TaliaIcons');
  static const IconData save = IconData(0xe080, fontFamily: 'TaliaIcons');
  static const IconData inbox = IconData(0xe081, fontFamily: 'TaliaIcons');
  static const IconData link = IconData(0xe082, fontFamily: 'TaliaIcons');
  static const IconData linkOff = IconData(0xe083, fontFamily: 'TaliaIcons');
  static const IconData login = IconData(0xe084, fontFamily: 'TaliaIcons');
  static const IconData logout = IconData(0xe085, fontFamily: 'TaliaIcons');
  static const IconData email = IconData(0xe086, fontFamily: 'TaliaIcons');
  static const IconData location = IconData(0xe087, fontFamily: 'TaliaIcons');
  static const IconData image = IconData(0xe088, fontFamily: 'TaliaIcons');
  static const IconData pdf = IconData(0xe089, fontFamily: 'TaliaIcons');
  static const IconData qrCode = IconData(0xe08a, fontFamily: 'TaliaIcons');
  static const IconData qrScan = IconData(0xe08b, fontFamily: 'TaliaIcons');
  static const IconData keyboard = IconData(0xe08c, fontFamily: 'TaliaIcons');
  static const IconData phone = IconData(0xe08d, fontFamily: 'TaliaIcons');
  static const IconData storage = IconData(0xe08e, fontFamily: 'TaliaIcons');
  static const IconData palette = IconData(0xe08f, fontFamily: 'TaliaIcons');
  static const IconData textSize = IconData(0xe090, fontFamily: 'TaliaIcons');
  static const IconData textIncrease = IconData(
    0xe091,
    fontFamily: 'TaliaIcons',
  );
  static const IconData textDecrease = IconData(
    0xe092,
    fontFamily: 'TaliaIcons',
  );
  static const IconData shortText = IconData(
    0xe093,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData listBulleted = IconData(
    0xe094,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData listNumbered = IconData(
    0xe095,
    fontFamily: 'TaliaIcons',
  );
  static const IconData checklist = IconData(0xe096, fontFamily: 'TaliaIcons');
  static const IconData factCheck = IconData(0xe097, fontFamily: 'TaliaIcons');
  static const IconData pending = IconData(0xe098, fontFamily: 'TaliaIcons');
  static const IconData note = IconData(
    0xe099,
    fontFamily: 'TaliaIcons',
    matchTextDirection: true,
  );
  static const IconData topic = IconData(0xe09a, fontFamily: 'TaliaIcons');
  static const IconData dashboard = IconData(0xe09b, fontFamily: 'TaliaIcons');
  static const IconData layoutSquare = IconData(
    0xe09c,
    fontFamily: 'TaliaIcons',
  );
  static const IconData layoutPortrait = IconData(
    0xe09d,
    fontFamily: 'TaliaIcons',
  );
  static const IconData fullscreen = IconData(0xe09e, fontFamily: 'TaliaIcons');
  static const IconData fullscreenExit = IconData(
    0xe09f,
    fontFamily: 'TaliaIcons',
  );
  static const IconData bell = IconData(0xe0a0, fontFamily: 'TaliaIcons');
  static const IconData calendar = IconData(0xe0a1, fontFamily: 'TaliaIcons');
  static const IconData calendarRange = IconData(
    0xe0a2,
    fontFamily: 'TaliaIcons',
  );
  static const IconData calendarCheck = IconData(
    0xe0a3,
    fontFamily: 'TaliaIcons',
  );
  static const IconData calendarEdit = IconData(
    0xe0a4,
    fontFamily: 'TaliaIcons',
  );
  static const IconData clock = IconData(0xe0a5, fontFamily: 'TaliaIcons');
  static const IconData timer = IconData(0xe0a6, fontFamily: 'TaliaIcons');
  static const IconData alarm = IconData(0xe0a7, fontFamily: 'TaliaIcons');
  static const IconData hourglass = IconData(0xe0a8, fontFamily: 'TaliaIcons');
  static const IconData update = IconData(0xe0a9, fontFamily: 'TaliaIcons');
  static const IconData history = IconData(0xe0aa, fontFamily: 'TaliaIcons');
}

/// Kids variant of [TaliaIcons]: same names and meanings, 2.5 stroke,
/// the nuqta drawn as a soft sparkle.
abstract final class TaliaKidsIcons {
  static const IconData home = IconData(0xe000, fontFamily: 'TaliaIconsKids');
  static const IconData mushaf = IconData(0xe001, fontFamily: 'TaliaIconsKids');
  static const IconData reading = IconData(
    0xe002,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData hifz = IconData(0xe003, fontFamily: 'TaliaIconsKids');
  static const IconData recite = IconData(0xe004, fontFamily: 'TaliaIconsKids');
  static const IconData mic = IconData(0xe005, fontFamily: 'TaliaIconsKids');
  static const IconData azkar = IconData(0xe006, fontFamily: 'TaliaIconsKids');
  static const IconData dua = IconData(0xe007, fontFamily: 'TaliaIconsKids');
  static const IconData prayer = IconData(0xe008, fontFamily: 'TaliaIconsKids');
  static const IconData flame = IconData(0xe009, fontFamily: 'TaliaIconsKids');
  static const IconData medal = IconData(0xe00a, fontFamily: 'TaliaIconsKids');
  static const IconData certificate = IconData(
    0xe00b,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData trophy = IconData(0xe00c, fontFamily: 'TaliaIconsKids');
  static const IconData progress = IconData(
    0xe00d,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData sparkle = IconData(
    0xe00e,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData journey = IconData(
    0xe00f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData listen = IconData(0xe010, fontFamily: 'TaliaIconsKids');
  static const IconData family = IconData(0xe011, fontFamily: 'TaliaIconsKids');
  static const IconData child = IconData(0xe012, fontFamily: 'TaliaIconsKids');
  static const IconData people = IconData(0xe013, fontFamily: 'TaliaIconsKids');
  static const IconData person = IconData(0xe014, fontFamily: 'TaliaIconsKids');
  static const IconData guardian = IconData(
    0xe015,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData shield = IconData(0xe016, fontFamily: 'TaliaIconsKids');
  static const IconData shieldCheck = IconData(
    0xe017,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData verified = IconData(
    0xe018,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData library = IconData(
    0xe019,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData readerMode = IconData(
    0xe01a,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData waveform = IconData(
    0xe01b,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData sun = IconData(0xe01c, fontFamily: 'TaliaIconsKids');
  static const IconData moon = IconData(0xe01d, fontFamily: 'TaliaIconsKids');
  static const IconData sunrise = IconData(
    0xe01e,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData cloudSun = IconData(
    0xe01f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData themeAuto = IconData(
    0xe020,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData contrast = IconData(
    0xe021,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData flag = IconData(0xe022, fontFamily: 'TaliaIconsKids');
  static const IconData school = IconData(0xe023, fontFamily: 'TaliaIconsKids');
  static const IconData idea = IconData(0xe024, fontFamily: 'TaliaIconsKids');
  static const IconData bolt = IconData(0xe025, fontFamily: 'TaliaIconsKids');
  static const IconData rocket = IconData(0xe026, fontFamily: 'TaliaIconsKids');
  static const IconData celebrate = IconData(
    0xe027,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData gift = IconData(0xe028, fontFamily: 'TaliaIconsKids');
  static const IconData gem = IconData(0xe029, fontFamily: 'TaliaIconsKids');
  static const IconData wave = IconData(0xe02a, fontFamily: 'TaliaIconsKids');
  static const IconData smile = IconData(0xe02b, fontFamily: 'TaliaIconsKids');
  static const IconData meh = IconData(0xe02c, fontFamily: 'TaliaIconsKids');
  static const IconData frown = IconData(0xe02d, fontFamily: 'TaliaIconsKids');
  static const IconData tree = IconData(0xe02e, fontFamily: 'TaliaIconsKids');
  static const IconData flower = IconData(0xe02f, fontFamily: 'TaliaIconsKids');
  static const IconData mountain = IconData(
    0xe030,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData water = IconData(0xe031, fontFamily: 'TaliaIconsKids');
  static const IconData heal = IconData(0xe032, fontFamily: 'TaliaIconsKids');
  static const IconData hub = IconData(0xe033, fontFamily: 'TaliaIconsKids');
  static const IconData balance = IconData(
    0xe034,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData chart = IconData(0xe035, fontFamily: 'TaliaIconsKids');
  static const IconData trendingDown = IconData(
    0xe036,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData tap = IconData(0xe037, fontFamily: 'TaliaIconsKids');
  static const IconData translate = IconData(
    0xe038,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData quote = IconData(0xe039, fontFamily: 'TaliaIconsKids');
  static const IconData star = IconData(0xe03a, fontFamily: 'TaliaIconsKids');
  static const IconData starFilled = IconData(
    0xe03b,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData starHalf = IconData(
    0xe03c,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData bookmark = IconData(
    0xe03d,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData bookmarkFilled = IconData(
    0xe03e,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData bookmarkCheck = IconData(
    0xe03f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData heartFilled = IconData(
    0xe040,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData circle = IconData(0xe041, fontFamily: 'TaliaIconsKids');
  static const IconData circleFilled = IconData(
    0xe042,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData target = IconData(0xe043, fontFamily: 'TaliaIconsKids');
  static const IconData checkCircle = IconData(
    0xe044,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData checkCircleFilled = IconData(
    0xe045,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData playCircle = IconData(
    0xe046,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData playCircleFilled = IconData(
    0xe047,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData pauseCircle = IconData(
    0xe048,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData pauseCircleFilled = IconData(
    0xe049,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData stopCircle = IconData(
    0xe04a,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData stopCircleFilled = IconData(
    0xe04b,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData play = IconData(0xe04c, fontFamily: 'TaliaIconsKids');
  static const IconData pause = IconData(0xe04d, fontFamily: 'TaliaIconsKids');
  static const IconData stop = IconData(0xe04e, fontFamily: 'TaliaIconsKids');
  static const IconData skipNext = IconData(
    0xe04f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData skipPrevious = IconData(
    0xe050,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData volume = IconData(0xe051, fontFamily: 'TaliaIconsKids');
  static const IconData volumeOff = IconData(
    0xe052,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData repeat = IconData(0xe053, fontFamily: 'TaliaIconsKids');
  static const IconData shuffle = IconData(
    0xe054,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData arrowBack = IconData(
    0xe055,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData arrowForward = IconData(
    0xe056,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData chevronBack = IconData(
    0xe057,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData chevronForward = IconData(
    0xe058,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData chevronDown = IconData(
    0xe059,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData firstPage = IconData(
    0xe05a,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData lastPage = IconData(
    0xe05b,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData swapVertical = IconData(
    0xe05c,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData swapHorizontal = IconData(
    0xe05d,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData externalLink = IconData(
    0xe05e,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData send = IconData(
    0xe05f,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData undo = IconData(
    0xe060,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData close = IconData(0xe061, fontFamily: 'TaliaIconsKids');
  static const IconData check = IconData(0xe062, fontFamily: 'TaliaIconsKids');
  static const IconData add = IconData(0xe063, fontFamily: 'TaliaIconsKids');
  static const IconData addCircle = IconData(
    0xe064,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData addTask = IconData(
    0xe065,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData refresh = IconData(
    0xe066,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData replay = IconData(0xe067, fontFamily: 'TaliaIconsKids');
  static const IconData share = IconData(0xe068, fontFamily: 'TaliaIconsKids');
  static const IconData shareUp = IconData(
    0xe069,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData copy = IconData(0xe06a, fontFamily: 'TaliaIconsKids');
  static const IconData edit = IconData(0xe06b, fontFamily: 'TaliaIconsKids');
  static const IconData delete = IconData(0xe06c, fontFamily: 'TaliaIconsKids');
  static const IconData deleteForever = IconData(
    0xe06d,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData search = IconData(0xe06e, fontFamily: 'TaliaIconsKids');
  static const IconData searchOff = IconData(
    0xe06f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData settings = IconData(
    0xe070,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData settingsSmart = IconData(
    0xe071,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData tune = IconData(0xe072, fontFamily: 'TaliaIconsKids');
  static const IconData more = IconData(0xe073, fontFamily: 'TaliaIconsKids');
  static const IconData show = IconData(0xe074, fontFamily: 'TaliaIconsKids');
  static const IconData hide = IconData(0xe075, fontFamily: 'TaliaIconsKids');
  static const IconData lock = IconData(0xe076, fontFamily: 'TaliaIconsKids');
  static const IconData lockReset = IconData(
    0xe077,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData key = IconData(0xe078, fontFamily: 'TaliaIconsKids');
  static const IconData info = IconData(0xe079, fontFamily: 'TaliaIconsKids');
  static const IconData error = IconData(0xe07a, fontFamily: 'TaliaIconsKids');
  static const IconData warning = IconData(
    0xe07b,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData cloudOff = IconData(
    0xe07c,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData cloudUpload = IconData(
    0xe07d,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData wifiOff = IconData(
    0xe07e,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData download = IconData(
    0xe07f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData save = IconData(0xe080, fontFamily: 'TaliaIconsKids');
  static const IconData inbox = IconData(0xe081, fontFamily: 'TaliaIconsKids');
  static const IconData link = IconData(0xe082, fontFamily: 'TaliaIconsKids');
  static const IconData linkOff = IconData(
    0xe083,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData login = IconData(0xe084, fontFamily: 'TaliaIconsKids');
  static const IconData logout = IconData(0xe085, fontFamily: 'TaliaIconsKids');
  static const IconData email = IconData(0xe086, fontFamily: 'TaliaIconsKids');
  static const IconData location = IconData(
    0xe087,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData image = IconData(0xe088, fontFamily: 'TaliaIconsKids');
  static const IconData pdf = IconData(0xe089, fontFamily: 'TaliaIconsKids');
  static const IconData qrCode = IconData(0xe08a, fontFamily: 'TaliaIconsKids');
  static const IconData qrScan = IconData(0xe08b, fontFamily: 'TaliaIconsKids');
  static const IconData keyboard = IconData(
    0xe08c,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData phone = IconData(0xe08d, fontFamily: 'TaliaIconsKids');
  static const IconData storage = IconData(
    0xe08e,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData palette = IconData(
    0xe08f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData textSize = IconData(
    0xe090,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData textIncrease = IconData(
    0xe091,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData textDecrease = IconData(
    0xe092,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData shortText = IconData(
    0xe093,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData listBulleted = IconData(
    0xe094,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData listNumbered = IconData(
    0xe095,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData checklist = IconData(
    0xe096,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData factCheck = IconData(
    0xe097,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData pending = IconData(
    0xe098,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData note = IconData(
    0xe099,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  );
  static const IconData topic = IconData(0xe09a, fontFamily: 'TaliaIconsKids');
  static const IconData dashboard = IconData(
    0xe09b,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData layoutSquare = IconData(
    0xe09c,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData layoutPortrait = IconData(
    0xe09d,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData fullscreen = IconData(
    0xe09e,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData fullscreenExit = IconData(
    0xe09f,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData bell = IconData(0xe0a0, fontFamily: 'TaliaIconsKids');
  static const IconData calendar = IconData(
    0xe0a1,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData calendarRange = IconData(
    0xe0a2,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData calendarCheck = IconData(
    0xe0a3,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData calendarEdit = IconData(
    0xe0a4,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData clock = IconData(0xe0a5, fontFamily: 'TaliaIconsKids');
  static const IconData timer = IconData(0xe0a6, fontFamily: 'TaliaIconsKids');
  static const IconData alarm = IconData(0xe0a7, fontFamily: 'TaliaIconsKids');
  static const IconData hourglass = IconData(
    0xe0a8,
    fontFamily: 'TaliaIconsKids',
  );
  static const IconData update = IconData(0xe0a9, fontFamily: 'TaliaIconsKids');
  static const IconData history = IconData(
    0xe0aa,
    fontFamily: 'TaliaIconsKids',
  );
}

/// Gold nuqta/accent layer for adult icons, keyed by codepoint.
const Map<int, IconData> taliaAccentLayers = <int, IconData>{
  0xe000: IconData(0xe800, fontFamily: 'TaliaIcons'),
  0xe001: IconData(0xe801, fontFamily: 'TaliaIcons'),
  0xe002: IconData(0xe802, fontFamily: 'TaliaIcons'),
  0xe003: IconData(0xe803, fontFamily: 'TaliaIcons'),
  0xe004: IconData(0xe804, fontFamily: 'TaliaIcons'),
  0xe005: IconData(0xe805, fontFamily: 'TaliaIcons'),
  0xe006: IconData(0xe806, fontFamily: 'TaliaIcons'),
  0xe007: IconData(0xe807, fontFamily: 'TaliaIcons'),
  0xe008: IconData(0xe808, fontFamily: 'TaliaIcons'),
  0xe009: IconData(0xe809, fontFamily: 'TaliaIcons'),
  0xe00a: IconData(0xe80a, fontFamily: 'TaliaIcons'),
  0xe00b: IconData(0xe80b, fontFamily: 'TaliaIcons'),
  0xe00c: IconData(0xe80c, fontFamily: 'TaliaIcons'),
  0xe00d: IconData(0xe80d, fontFamily: 'TaliaIcons', matchTextDirection: true),
  0xe00e: IconData(0xe80e, fontFamily: 'TaliaIcons'),
  0xe00f: IconData(0xe80f, fontFamily: 'TaliaIcons'),
  0xe010: IconData(0xe810, fontFamily: 'TaliaIcons'),
};

/// Sparkle/accent layer for kids icons, keyed by codepoint.
const Map<int, IconData> taliaKidsAccentLayers = <int, IconData>{
  0xe000: IconData(0xe800, fontFamily: 'TaliaIconsKids'),
  0xe001: IconData(0xe801, fontFamily: 'TaliaIconsKids'),
  0xe002: IconData(0xe802, fontFamily: 'TaliaIconsKids'),
  0xe003: IconData(0xe803, fontFamily: 'TaliaIconsKids'),
  0xe004: IconData(0xe804, fontFamily: 'TaliaIconsKids'),
  0xe005: IconData(0xe805, fontFamily: 'TaliaIconsKids'),
  0xe006: IconData(0xe806, fontFamily: 'TaliaIconsKids'),
  0xe007: IconData(0xe807, fontFamily: 'TaliaIconsKids'),
  0xe008: IconData(0xe808, fontFamily: 'TaliaIconsKids'),
  0xe009: IconData(0xe809, fontFamily: 'TaliaIconsKids'),
  0xe00a: IconData(0xe80a, fontFamily: 'TaliaIconsKids'),
  0xe00b: IconData(0xe80b, fontFamily: 'TaliaIconsKids'),
  0xe00c: IconData(0xe80c, fontFamily: 'TaliaIconsKids'),
  0xe00d: IconData(
    0xe80d,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  ),
  0xe00e: IconData(0xe80e, fontFamily: 'TaliaIconsKids'),
  0xe00f: IconData(0xe80f, fontFamily: 'TaliaIconsKids'),
  0xe010: IconData(0xe810, fontFamily: 'TaliaIconsKids'),
};

/// Tint layer drawn under kids icons, keyed by codepoint.
const Map<int, IconData> taliaKidsFillLayers = <int, IconData>{
  0xe000: IconData(0xf000, fontFamily: 'TaliaIconsKids'),
  0xe001: IconData(0xf001, fontFamily: 'TaliaIconsKids'),
  0xe002: IconData(0xf002, fontFamily: 'TaliaIconsKids'),
  0xe003: IconData(0xf003, fontFamily: 'TaliaIconsKids'),
  0xe004: IconData(0xf004, fontFamily: 'TaliaIconsKids'),
  0xe005: IconData(0xf005, fontFamily: 'TaliaIconsKids'),
  0xe006: IconData(0xf006, fontFamily: 'TaliaIconsKids'),
  0xe007: IconData(0xf007, fontFamily: 'TaliaIconsKids'),
  0xe008: IconData(0xf008, fontFamily: 'TaliaIconsKids'),
  0xe009: IconData(0xf009, fontFamily: 'TaliaIconsKids'),
  0xe00a: IconData(0xf00a, fontFamily: 'TaliaIconsKids'),
  0xe00b: IconData(0xf00b, fontFamily: 'TaliaIconsKids'),
  0xe00c: IconData(0xf00c, fontFamily: 'TaliaIconsKids'),
  0xe00d: IconData(
    0xf00d,
    fontFamily: 'TaliaIconsKids',
    matchTextDirection: true,
  ),
  0xe00e: IconData(0xf00e, fontFamily: 'TaliaIconsKids'),
  0xe00f: IconData(0xf00f, fontFamily: 'TaliaIconsKids'),
  0xe010: IconData(0xf010, fontFamily: 'TaliaIconsKids'),
  0xe011: IconData(0xf011, fontFamily: 'TaliaIconsKids'),
};

/// Kids glyph for each adult glyph, keyed by codepoint.
const Map<int, IconData> taliaKidsVariants = <int, IconData>{
  0xe000: TaliaKidsIcons.home,
  0xe001: TaliaKidsIcons.mushaf,
  0xe002: TaliaKidsIcons.reading,
  0xe003: TaliaKidsIcons.hifz,
  0xe004: TaliaKidsIcons.recite,
  0xe005: TaliaKidsIcons.mic,
  0xe006: TaliaKidsIcons.azkar,
  0xe007: TaliaKidsIcons.dua,
  0xe008: TaliaKidsIcons.prayer,
  0xe009: TaliaKidsIcons.flame,
  0xe00a: TaliaKidsIcons.medal,
  0xe00b: TaliaKidsIcons.certificate,
  0xe00c: TaliaKidsIcons.trophy,
  0xe00d: TaliaKidsIcons.progress,
  0xe00e: TaliaKidsIcons.sparkle,
  0xe00f: TaliaKidsIcons.journey,
  0xe010: TaliaKidsIcons.listen,
  0xe011: TaliaKidsIcons.family,
  0xe012: TaliaKidsIcons.child,
  0xe013: TaliaKidsIcons.people,
  0xe014: TaliaKidsIcons.person,
  0xe015: TaliaKidsIcons.guardian,
  0xe016: TaliaKidsIcons.shield,
  0xe017: TaliaKidsIcons.shieldCheck,
  0xe018: TaliaKidsIcons.verified,
  0xe019: TaliaKidsIcons.library,
  0xe01a: TaliaKidsIcons.readerMode,
  0xe01b: TaliaKidsIcons.waveform,
  0xe01c: TaliaKidsIcons.sun,
  0xe01d: TaliaKidsIcons.moon,
  0xe01e: TaliaKidsIcons.sunrise,
  0xe01f: TaliaKidsIcons.cloudSun,
  0xe020: TaliaKidsIcons.themeAuto,
  0xe021: TaliaKidsIcons.contrast,
  0xe022: TaliaKidsIcons.flag,
  0xe023: TaliaKidsIcons.school,
  0xe024: TaliaKidsIcons.idea,
  0xe025: TaliaKidsIcons.bolt,
  0xe026: TaliaKidsIcons.rocket,
  0xe027: TaliaKidsIcons.celebrate,
  0xe028: TaliaKidsIcons.gift,
  0xe029: TaliaKidsIcons.gem,
  0xe02a: TaliaKidsIcons.wave,
  0xe02b: TaliaKidsIcons.smile,
  0xe02c: TaliaKidsIcons.meh,
  0xe02d: TaliaKidsIcons.frown,
  0xe02e: TaliaKidsIcons.tree,
  0xe02f: TaliaKidsIcons.flower,
  0xe030: TaliaKidsIcons.mountain,
  0xe031: TaliaKidsIcons.water,
  0xe032: TaliaKidsIcons.heal,
  0xe033: TaliaKidsIcons.hub,
  0xe034: TaliaKidsIcons.balance,
  0xe035: TaliaKidsIcons.chart,
  0xe036: TaliaKidsIcons.trendingDown,
  0xe037: TaliaKidsIcons.tap,
  0xe038: TaliaKidsIcons.translate,
  0xe039: TaliaKidsIcons.quote,
  0xe03a: TaliaKidsIcons.star,
  0xe03b: TaliaKidsIcons.starFilled,
  0xe03c: TaliaKidsIcons.starHalf,
  0xe03d: TaliaKidsIcons.bookmark,
  0xe03e: TaliaKidsIcons.bookmarkFilled,
  0xe03f: TaliaKidsIcons.bookmarkCheck,
  0xe040: TaliaKidsIcons.heartFilled,
  0xe041: TaliaKidsIcons.circle,
  0xe042: TaliaKidsIcons.circleFilled,
  0xe043: TaliaKidsIcons.target,
  0xe044: TaliaKidsIcons.checkCircle,
  0xe045: TaliaKidsIcons.checkCircleFilled,
  0xe046: TaliaKidsIcons.playCircle,
  0xe047: TaliaKidsIcons.playCircleFilled,
  0xe048: TaliaKidsIcons.pauseCircle,
  0xe049: TaliaKidsIcons.pauseCircleFilled,
  0xe04a: TaliaKidsIcons.stopCircle,
  0xe04b: TaliaKidsIcons.stopCircleFilled,
  0xe04c: TaliaKidsIcons.play,
  0xe04d: TaliaKidsIcons.pause,
  0xe04e: TaliaKidsIcons.stop,
  0xe04f: TaliaKidsIcons.skipNext,
  0xe050: TaliaKidsIcons.skipPrevious,
  0xe051: TaliaKidsIcons.volume,
  0xe052: TaliaKidsIcons.volumeOff,
  0xe053: TaliaKidsIcons.repeat,
  0xe054: TaliaKidsIcons.shuffle,
  0xe055: TaliaKidsIcons.arrowBack,
  0xe056: TaliaKidsIcons.arrowForward,
  0xe057: TaliaKidsIcons.chevronBack,
  0xe058: TaliaKidsIcons.chevronForward,
  0xe059: TaliaKidsIcons.chevronDown,
  0xe05a: TaliaKidsIcons.firstPage,
  0xe05b: TaliaKidsIcons.lastPage,
  0xe05c: TaliaKidsIcons.swapVertical,
  0xe05d: TaliaKidsIcons.swapHorizontal,
  0xe05e: TaliaKidsIcons.externalLink,
  0xe05f: TaliaKidsIcons.send,
  0xe060: TaliaKidsIcons.undo,
  0xe061: TaliaKidsIcons.close,
  0xe062: TaliaKidsIcons.check,
  0xe063: TaliaKidsIcons.add,
  0xe064: TaliaKidsIcons.addCircle,
  0xe065: TaliaKidsIcons.addTask,
  0xe066: TaliaKidsIcons.refresh,
  0xe067: TaliaKidsIcons.replay,
  0xe068: TaliaKidsIcons.share,
  0xe069: TaliaKidsIcons.shareUp,
  0xe06a: TaliaKidsIcons.copy,
  0xe06b: TaliaKidsIcons.edit,
  0xe06c: TaliaKidsIcons.delete,
  0xe06d: TaliaKidsIcons.deleteForever,
  0xe06e: TaliaKidsIcons.search,
  0xe06f: TaliaKidsIcons.searchOff,
  0xe070: TaliaKidsIcons.settings,
  0xe071: TaliaKidsIcons.settingsSmart,
  0xe072: TaliaKidsIcons.tune,
  0xe073: TaliaKidsIcons.more,
  0xe074: TaliaKidsIcons.show,
  0xe075: TaliaKidsIcons.hide,
  0xe076: TaliaKidsIcons.lock,
  0xe077: TaliaKidsIcons.lockReset,
  0xe078: TaliaKidsIcons.key,
  0xe079: TaliaKidsIcons.info,
  0xe07a: TaliaKidsIcons.error,
  0xe07b: TaliaKidsIcons.warning,
  0xe07c: TaliaKidsIcons.cloudOff,
  0xe07d: TaliaKidsIcons.cloudUpload,
  0xe07e: TaliaKidsIcons.wifiOff,
  0xe07f: TaliaKidsIcons.download,
  0xe080: TaliaKidsIcons.save,
  0xe081: TaliaKidsIcons.inbox,
  0xe082: TaliaKidsIcons.link,
  0xe083: TaliaKidsIcons.linkOff,
  0xe084: TaliaKidsIcons.login,
  0xe085: TaliaKidsIcons.logout,
  0xe086: TaliaKidsIcons.email,
  0xe087: TaliaKidsIcons.location,
  0xe088: TaliaKidsIcons.image,
  0xe089: TaliaKidsIcons.pdf,
  0xe08a: TaliaKidsIcons.qrCode,
  0xe08b: TaliaKidsIcons.qrScan,
  0xe08c: TaliaKidsIcons.keyboard,
  0xe08d: TaliaKidsIcons.phone,
  0xe08e: TaliaKidsIcons.storage,
  0xe08f: TaliaKidsIcons.palette,
  0xe090: TaliaKidsIcons.textSize,
  0xe091: TaliaKidsIcons.textIncrease,
  0xe092: TaliaKidsIcons.textDecrease,
  0xe093: TaliaKidsIcons.shortText,
  0xe094: TaliaKidsIcons.listBulleted,
  0xe095: TaliaKidsIcons.listNumbered,
  0xe096: TaliaKidsIcons.checklist,
  0xe097: TaliaKidsIcons.factCheck,
  0xe098: TaliaKidsIcons.pending,
  0xe099: TaliaKidsIcons.note,
  0xe09a: TaliaKidsIcons.topic,
  0xe09b: TaliaKidsIcons.dashboard,
  0xe09c: TaliaKidsIcons.layoutSquare,
  0xe09d: TaliaKidsIcons.layoutPortrait,
  0xe09e: TaliaKidsIcons.fullscreen,
  0xe09f: TaliaKidsIcons.fullscreenExit,
  0xe0a0: TaliaKidsIcons.bell,
  0xe0a1: TaliaKidsIcons.calendar,
  0xe0a2: TaliaKidsIcons.calendarRange,
  0xe0a3: TaliaKidsIcons.calendarCheck,
  0xe0a4: TaliaKidsIcons.calendarEdit,
  0xe0a5: TaliaKidsIcons.clock,
  0xe0a6: TaliaKidsIcons.timer,
  0xe0a7: TaliaKidsIcons.alarm,
  0xe0a8: TaliaKidsIcons.hourglass,
  0xe0a9: TaliaKidsIcons.update,
  0xe0aa: TaliaKidsIcons.history,
};

/// Every icon by name (gallery, tests).
const Map<String, IconData> taliaIconsByName = <String, IconData>{
  'home': TaliaIcons.home,
  'mushaf': TaliaIcons.mushaf,
  'reading': TaliaIcons.reading,
  'hifz': TaliaIcons.hifz,
  'recite': TaliaIcons.recite,
  'mic': TaliaIcons.mic,
  'azkar': TaliaIcons.azkar,
  'dua': TaliaIcons.dua,
  'prayer': TaliaIcons.prayer,
  'flame': TaliaIcons.flame,
  'medal': TaliaIcons.medal,
  'certificate': TaliaIcons.certificate,
  'trophy': TaliaIcons.trophy,
  'progress': TaliaIcons.progress,
  'sparkle': TaliaIcons.sparkle,
  'journey': TaliaIcons.journey,
  'listen': TaliaIcons.listen,
  'family': TaliaIcons.family,
  'child': TaliaIcons.child,
  'people': TaliaIcons.people,
  'person': TaliaIcons.person,
  'guardian': TaliaIcons.guardian,
  'shield': TaliaIcons.shield,
  'shieldCheck': TaliaIcons.shieldCheck,
  'verified': TaliaIcons.verified,
  'library': TaliaIcons.library,
  'readerMode': TaliaIcons.readerMode,
  'waveform': TaliaIcons.waveform,
  'sun': TaliaIcons.sun,
  'moon': TaliaIcons.moon,
  'sunrise': TaliaIcons.sunrise,
  'cloudSun': TaliaIcons.cloudSun,
  'themeAuto': TaliaIcons.themeAuto,
  'contrast': TaliaIcons.contrast,
  'flag': TaliaIcons.flag,
  'school': TaliaIcons.school,
  'idea': TaliaIcons.idea,
  'bolt': TaliaIcons.bolt,
  'rocket': TaliaIcons.rocket,
  'celebrate': TaliaIcons.celebrate,
  'gift': TaliaIcons.gift,
  'gem': TaliaIcons.gem,
  'wave': TaliaIcons.wave,
  'smile': TaliaIcons.smile,
  'meh': TaliaIcons.meh,
  'frown': TaliaIcons.frown,
  'tree': TaliaIcons.tree,
  'flower': TaliaIcons.flower,
  'mountain': TaliaIcons.mountain,
  'water': TaliaIcons.water,
  'heal': TaliaIcons.heal,
  'hub': TaliaIcons.hub,
  'balance': TaliaIcons.balance,
  'chart': TaliaIcons.chart,
  'trendingDown': TaliaIcons.trendingDown,
  'tap': TaliaIcons.tap,
  'translate': TaliaIcons.translate,
  'quote': TaliaIcons.quote,
  'star': TaliaIcons.star,
  'starFilled': TaliaIcons.starFilled,
  'starHalf': TaliaIcons.starHalf,
  'bookmark': TaliaIcons.bookmark,
  'bookmarkFilled': TaliaIcons.bookmarkFilled,
  'bookmarkCheck': TaliaIcons.bookmarkCheck,
  'heartFilled': TaliaIcons.heartFilled,
  'circle': TaliaIcons.circle,
  'circleFilled': TaliaIcons.circleFilled,
  'target': TaliaIcons.target,
  'checkCircle': TaliaIcons.checkCircle,
  'checkCircleFilled': TaliaIcons.checkCircleFilled,
  'playCircle': TaliaIcons.playCircle,
  'playCircleFilled': TaliaIcons.playCircleFilled,
  'pauseCircle': TaliaIcons.pauseCircle,
  'pauseCircleFilled': TaliaIcons.pauseCircleFilled,
  'stopCircle': TaliaIcons.stopCircle,
  'stopCircleFilled': TaliaIcons.stopCircleFilled,
  'play': TaliaIcons.play,
  'pause': TaliaIcons.pause,
  'stop': TaliaIcons.stop,
  'skipNext': TaliaIcons.skipNext,
  'skipPrevious': TaliaIcons.skipPrevious,
  'volume': TaliaIcons.volume,
  'volumeOff': TaliaIcons.volumeOff,
  'repeat': TaliaIcons.repeat,
  'shuffle': TaliaIcons.shuffle,
  'arrowBack': TaliaIcons.arrowBack,
  'arrowForward': TaliaIcons.arrowForward,
  'chevronBack': TaliaIcons.chevronBack,
  'chevronForward': TaliaIcons.chevronForward,
  'chevronDown': TaliaIcons.chevronDown,
  'firstPage': TaliaIcons.firstPage,
  'lastPage': TaliaIcons.lastPage,
  'swapVertical': TaliaIcons.swapVertical,
  'swapHorizontal': TaliaIcons.swapHorizontal,
  'externalLink': TaliaIcons.externalLink,
  'send': TaliaIcons.send,
  'undo': TaliaIcons.undo,
  'close': TaliaIcons.close,
  'check': TaliaIcons.check,
  'add': TaliaIcons.add,
  'addCircle': TaliaIcons.addCircle,
  'addTask': TaliaIcons.addTask,
  'refresh': TaliaIcons.refresh,
  'replay': TaliaIcons.replay,
  'share': TaliaIcons.share,
  'shareUp': TaliaIcons.shareUp,
  'copy': TaliaIcons.copy,
  'edit': TaliaIcons.edit,
  'delete': TaliaIcons.delete,
  'deleteForever': TaliaIcons.deleteForever,
  'search': TaliaIcons.search,
  'searchOff': TaliaIcons.searchOff,
  'settings': TaliaIcons.settings,
  'settingsSmart': TaliaIcons.settingsSmart,
  'tune': TaliaIcons.tune,
  'more': TaliaIcons.more,
  'show': TaliaIcons.show,
  'hide': TaliaIcons.hide,
  'lock': TaliaIcons.lock,
  'lockReset': TaliaIcons.lockReset,
  'key': TaliaIcons.key,
  'info': TaliaIcons.info,
  'error': TaliaIcons.error,
  'warning': TaliaIcons.warning,
  'cloudOff': TaliaIcons.cloudOff,
  'cloudUpload': TaliaIcons.cloudUpload,
  'wifiOff': TaliaIcons.wifiOff,
  'download': TaliaIcons.download,
  'save': TaliaIcons.save,
  'inbox': TaliaIcons.inbox,
  'link': TaliaIcons.link,
  'linkOff': TaliaIcons.linkOff,
  'login': TaliaIcons.login,
  'logout': TaliaIcons.logout,
  'email': TaliaIcons.email,
  'location': TaliaIcons.location,
  'image': TaliaIcons.image,
  'pdf': TaliaIcons.pdf,
  'qrCode': TaliaIcons.qrCode,
  'qrScan': TaliaIcons.qrScan,
  'keyboard': TaliaIcons.keyboard,
  'phone': TaliaIcons.phone,
  'storage': TaliaIcons.storage,
  'palette': TaliaIcons.palette,
  'textSize': TaliaIcons.textSize,
  'textIncrease': TaliaIcons.textIncrease,
  'textDecrease': TaliaIcons.textDecrease,
  'shortText': TaliaIcons.shortText,
  'listBulleted': TaliaIcons.listBulleted,
  'listNumbered': TaliaIcons.listNumbered,
  'checklist': TaliaIcons.checklist,
  'factCheck': TaliaIcons.factCheck,
  'pending': TaliaIcons.pending,
  'note': TaliaIcons.note,
  'topic': TaliaIcons.topic,
  'dashboard': TaliaIcons.dashboard,
  'layoutSquare': TaliaIcons.layoutSquare,
  'layoutPortrait': TaliaIcons.layoutPortrait,
  'fullscreen': TaliaIcons.fullscreen,
  'fullscreenExit': TaliaIcons.fullscreenExit,
  'bell': TaliaIcons.bell,
  'calendar': TaliaIcons.calendar,
  'calendarRange': TaliaIcons.calendarRange,
  'calendarCheck': TaliaIcons.calendarCheck,
  'calendarEdit': TaliaIcons.calendarEdit,
  'clock': TaliaIcons.clock,
  'timer': TaliaIcons.timer,
  'alarm': TaliaIcons.alarm,
  'hourglass': TaliaIcons.hourglass,
  'update': TaliaIcons.update,
  'history': TaliaIcons.history,
};
