param([string]$Ids='1,2,4,5')
$ErrorActionPreference='Stop';$root=$PSScriptRoot;$parent=Split-Path $root;$plan=Get-Content "$root/campaign-plan.json" -Raw|ConvertFrom-Json;$assets=@(Get-Content "$parent/superdesign-assets.json" -Raw|ConvertFrom-Json);$picked=@($Ids.Split(',')|ForEach-Object {[int]$_});$pair=@{1=11;2=1;4=5;5=4;6=4;7=8;8=7;9=1;10=4;11=12;12=11;13=11;14=11;15=12;16=11}
$argsList=@('--yes','@superdesign/cli@latest','iterate-design-draft','--draft-id','f4cd31e1-07ef-40ca-b268-d30f47cf854c','--mode','branch','--device','custom','--width','1080','--height','1920','--user-request','تمام الي حد ما قريب من الفكره . يمكنك تطويرها مع تغير الخط ليكون نفس الخط في التصميم الاول','--json');$refs=@('talia-official-logo')
foreach($id in $picked){$s=$plan.slides|Where-Object id -eq $id;$a=($assets|Where-Object name -eq $s.source).asset;$secondary=$plan.slides|Where-Object id -eq $pair[$id];$b=($assets|Where-Object name -eq $secondary.source).asset;$head=$s.headline.Replace("`n",' / ')
$layout=if($id%2 -eq 0){'Primary screenshot centered x225 y640 width660 rotated+3deg. Secondary behind on RIGHT x760 y940 width400 rotated-8deg, may bleed right edge.'}else{'Primary screenshot x300 y640 width660 rotated-5deg. Secondary behind on LEFT x-35 y940 width430 rotated+9deg, may bleed left edge.'}
$p="Poster $($id.ToString('00')) $($s.screen),1080x1920. Inherit base ivory/gold pattern, Reem Kufi86px bold header and34px support, original logo. EXACT headline two lines: $head. EXACT support: $($s.support). $layout Primary EXACT img $($a.url). Secondary EXACT img $($b.url). Primary fully visible at natural ratio, NO reader crop, no covered controls/Quran. Secondary behind. Keep all screenshot pixels unchanged, no fade/redraw. Header y175 margins90, support below. Soft shadows22px corners. Editable Arabic HTML. No CTA, phone frame, numbers or invented claims.";
if($id -eq 14){$p += 'For kids Quran reader, ALL Quran title and seven verses must remain visible and unobscured; use full uncropped screenshot.'}
$argsList+=@('-p',$p);$refs+=@($a.nodeId,$b.nodeId)}
$argsList+=@('--reference-id')+@($refs|Select-Object -Unique);$out=& npx @argsList;if($LASTEXITCODE -ne 0){throw 'Batch generation failed'};$out|Set-Content "$root/designs/batch-$Ids.json" -Encoding utf8;$batch=$out|ConvertFrom-Json
foreach($d in $batch.drafts){$json=& npx --yes @superdesign/cli@latest get-design --draft-id $d.draftId --json;if($LASTEXITCODE -ne 0){throw 'Read failed'};$json|Set-Content "$root/designs/unmapped-$($d.draftId).json" -Encoding utf8;Write-Output "Downloaded $($d.draftId)"}
