// Mocks generated by Mockito 5.4.4 from annotations
// in talia_quran/test/features/memorization_plus/presentation/cubits/guardian_linking_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talia_quran/core/error/app_failure.dart' as _i5;
import 'package:talia_quran/core/memorization/review_record_audience_scope.dart'
    as _i7;
import 'package:talia_quran/features/certificate/domain/entities/certificate_award.dart'
    as _i8;
import 'package:talia_quran/features/memorization_plus/domain/entities/memorization_entities.dart'
    as _i6;
import 'package:talia_quran/features/memorization_plus/domain/repositories/memorization_plus_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MemorizationPlusRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemorizationPlusRepository extends _i1.Mock
    implements _i3.MemorizationPlusRepository {
  MockMemorizationPlusRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      getMemorizationProfile() => (super.noSuchMethod(
            Invocation.method(
              #getMemorizationProfile,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #getMemorizationProfile,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      selectMemorizationPath(_i6.MemorizationPath? path) => (super.noSuchMethod(
            Invocation.method(
              #selectMemorizationPath,
              [path],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #selectMemorizationPath,
                [path],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      continueWithoutGuardian() => (super.noSuchMethod(
            Invocation.method(
              #continueWithoutGuardian,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #continueWithoutGuardian,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PairingSession>>
      createGuardianPairingSession() => (super.noSuchMethod(
            Invocation.method(
              #createGuardianPairingSession,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PairingSession>>.value(
                    _FakeEither_0<_i5.Failure, _i6.PairingSession>(
              this,
              Invocation.method(
                #createGuardianPairingSession,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PairingSession>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      acceptGuardianPairingCode(String? codeOrQrData) => (super.noSuchMethod(
            Invocation.method(
              #acceptGuardianPairingCode,
              [codeOrQrData],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #acceptGuardianPairingCode,
                [codeOrQrData],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PairingSession?>>
      refreshPairingSession() => (super.noSuchMethod(
            Invocation.method(
              #refreshPairingSession,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PairingSession?>>.value(
                    _FakeEither_0<_i5.Failure, _i6.PairingSession?>(
              this,
              Invocation.method(
                #refreshPairingSession,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PairingSession?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      unlinkGuardian() => (super.noSuchMethod(
            Invocation.method(
              #unlinkGuardian,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #unlinkGuardian,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      setParentGuardianMode(bool? value) => (super.noSuchMethod(
            Invocation.method(
              #setParentGuardianMode,
              [value],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #setParentGuardianMode,
                [value],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      refreshChildGuardianLink() => (super.noSuchMethod(
            Invocation.method(
              #refreshChildGuardianLink,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #refreshChildGuardianLink,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>
      resetMemorizationIdentity() => (super.noSuchMethod(
            Invocation.method(
              #resetMemorizationIdentity,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationProfile>(
              this,
              Invocation.method(
                #resetMemorizationIdentity,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SmartMemorizationSettings>>
      getSmartSettings() => (super.noSuchMethod(
            Invocation.method(
              #getSmartSettings,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, _i6.SmartMemorizationSettings>>.value(
                _FakeEither_0<_i5.Failure, _i6.SmartMemorizationSettings>(
              this,
              Invocation.method(
                #getSmartSettings,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i6.SmartMemorizationSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveSmartSettings(
          _i6.SmartMemorizationSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSmartSettings,
          [settings],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveSmartSettings,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i2.Either<_i5.Failure, _i6.MemorizationTrack?> getSelectedTrack() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedTrack,
          [],
        ),
        returnValue: _FakeEither_0<_i5.Failure, _i6.MemorizationTrack?>(
          this,
          Invocation.method(
            #getSelectedTrack,
            [],
          ),
        ),
      ) as _i2.Either<_i5.Failure, _i6.MemorizationTrack?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveSelectedTrack(
          _i6.MemorizationTrack? track) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedTrack,
          [track],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveSelectedTrack,
            [track],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan>> generateDailyPlan({
    required int? surahId,
    required int? newAyahsPerDay,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateDailyPlan,
          [],
          {
            #surahId: surahId,
            #newAyahsPerDay: newAyahsPerDay,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan>>.value(
            _FakeEither_0<_i5.Failure, _i6.DailyPlan>(
          this,
          Invocation.method(
            #generateDailyPlan,
            [],
            {
              #surahId: surahId,
              #newAyahsPerDay: newAyahsPerDay,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan?>> getCachedDailyPlan() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDailyPlan,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan?>>.value(
            _FakeEither_0<_i5.Failure, _i6.DailyPlan?>(
          this,
          Invocation.method(
            #getCachedDailyPlan,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveDailyPlan(
          _i6.DailyPlan? plan) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDailyPlan,
          [plan],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveDailyPlan,
            [plan],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> markDailyPlanAyahCompleted({
    required int? surahId,
    required int? ayahNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markDailyPlanAyahCompleted,
          [],
          {
            #surahId: surahId,
            #ayahNumber: ayahNumber,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #markDailyPlanAyahCompleted,
            [],
            {
              #surahId: surahId,
              #ayahNumber: ayahNumber,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AyahReviewRecord?>> getReviewRecord(
    int? surahId,
    int? ayahNumber, {
    _i7.ReviewRecordReadScope? scope = _i7.ReviewRecordReadScope.adult,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewRecord,
          [
            surahId,
            ayahNumber,
          ],
          {#scope: scope},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AyahReviewRecord?>>.value(
                _FakeEither_0<_i5.Failure, _i6.AyahReviewRecord?>(
          this,
          Invocation.method(
            #getReviewRecord,
            [
              surahId,
              ayahNumber,
            ],
            {#scope: scope},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AyahReviewRecord?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AyahReviewRecord>>>
      getAllReviewRecords(
              {_i7.ReviewRecordReadScope? scope =
                  _i7.ReviewRecordReadScope.adult}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAllReviewRecords,
              [],
              {#scope: scope},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.AyahReviewRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.AyahReviewRecord>>(
              this,
              Invocation.method(
                #getAllReviewRecords,
                [],
                {#scope: scope},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AyahReviewRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveReviewRecord(
          _i6.AyahReviewRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReviewRecord,
          [record],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveReviewRecord,
            [record],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.KidsProgress>> getKidsProgress() =>
      (super.noSuchMethod(
        Invocation.method(
          #getKidsProgress,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.KidsProgress>>.value(
                _FakeEither_0<_i5.Failure, _i6.KidsProgress>(
          this,
          Invocation.method(
            #getKidsProgress,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.KidsProgress>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveKidsProgress(
          _i6.KidsProgress? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKidsProgress,
          [progress],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveKidsProgress,
            [progress],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.KidsJourneyStage>>>
      getKidsJourney({required int? surahId}) => (super.noSuchMethod(
            Invocation.method(
              #getKidsJourney,
              [],
              {#surahId: surahId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.KidsJourneyStage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.KidsJourneyStage>>(
              this,
              Invocation.method(
                #getKidsJourney,
                [],
                {#surahId: surahId},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.KidsJourneyStage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.KidsSessionLog>>>
      getKidsSessionLogs() => (super.noSuchMethod(
            Invocation.method(
              #getKidsSessionLogs,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.KidsSessionLog>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.KidsSessionLog>>(
              this,
              Invocation.method(
                #getKidsSessionLogs,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.KidsSessionLog>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.KidsSessionLog>> saveKidsSessionLog({
    required int? surahId,
    required int? ayahNumber,
    required int? repeatsCompleted,
    required int? pointsEarned,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKidsSessionLog,
          [],
          {
            #surahId: surahId,
            #ayahNumber: ayahNumber,
            #repeatsCompleted: repeatsCompleted,
            #pointsEarned: pointsEarned,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.KidsSessionLog>>.value(
                _FakeEither_0<_i5.Failure, _i6.KidsSessionLog>(
          this,
          Invocation.method(
            #saveKidsSessionLog,
            [],
            {
              #surahId: surahId,
              #ayahNumber: ayahNumber,
              #repeatsCompleted: repeatsCompleted,
              #pointsEarned: pointsEarned,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.KidsSessionLog>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ParentDashboard>> getParentDashboard(
          {required int? surahId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParentDashboard,
          [],
          {#surahId: surahId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ParentDashboard>>.value(
                _FakeEither_0<_i5.Failure, _i6.ParentDashboard>(
          this,
          Invocation.method(
            #getParentDashboard,
            [],
            {#surahId: surahId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ParentDashboard>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ParentSettings>> getParentSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getParentSettings,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ParentSettings>>.value(
                _FakeEither_0<_i5.Failure, _i6.ParentSettings>(
          this,
          Invocation.method(
            #getParentSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ParentSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveParentSettings(
          _i6.ParentSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveParentSettings,
          [settings],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveParentSettings,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> verifyParentPin(String? pin) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyParentPin,
          [pin],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #verifyParentPin,
            [pin],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setParentPin(String? pin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setParentPin,
          [pin],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #setParentPin,
            [pin],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetParentAccess() =>
      (super.noSuchMethod(
        Invocation.method(
          #resetParentAccess,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetParentAccess,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>> saveParentReward(
          String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveParentReward,
          [title],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ParentReward>>(
          this,
          Invocation.method(
            #saveParentReward,
            [title],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>> claimParentReward(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimParentReward,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ParentReward>>(
          this,
          Invocation.method(
            #claimParentReward,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> createChildLinkToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #createChildLinkToken,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #createChildLinkToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> acceptChildLinkToken(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptChildLinkToken,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #acceptChildLinkToken,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> syncKidsProgressToCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncKidsProgressToCloud,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #syncKidsProgressToCloud,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RemoteChildSummary>>>
      getRemoteChildren() => (super.noSuchMethod(
            Invocation.method(
              #getRemoteChildren,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.RemoteChildSummary>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RemoteChildSummary>>(
              this,
              Invocation.method(
                #getRemoteChildren,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.RemoteChildSummary>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>
      saveRemoteParentReward({
    required String? childUserId,
    required String? title,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #saveRemoteParentReward,
              [],
              {
                #childUserId: childUserId,
                #title: title,
              },
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ParentReward>>(
              this,
              Invocation.method(
                #saveRemoteParentReward,
                [],
                {
                  #childUserId: childUserId,
                  #title: title,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParentReward>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.KidsCompletionResult>> awardKidsPoints({
    required int? surahId,
    required int? ayahNumber,
    required int? repeatsCompleted,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #awardKidsPoints,
          [],
          {
            #surahId: surahId,
            #ayahNumber: ayahNumber,
            #repeatsCompleted: repeatsCompleted,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.KidsCompletionResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.KidsCompletionResult>(
          this,
          Invocation.method(
            #awardKidsPoints,
            [],
            {
              #surahId: surahId,
              #ayahNumber: ayahNumber,
              #repeatsCompleted: repeatsCompleted,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.KidsCompletionResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CustomMemorizationPlan?>>
      getCustomPlan() => (super.noSuchMethod(
            Invocation.method(
              #getCustomPlan,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.CustomMemorizationPlan?>>.value(
                _FakeEither_0<_i5.Failure, _i6.CustomMemorizationPlan?>(
              this,
              Invocation.method(
                #getCustomPlan,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i6.CustomMemorizationPlan?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveCustomPlan(
          _i6.CustomMemorizationPlan? plan) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomPlan,
          [plan],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveCustomPlan,
            [plan],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCustomPlan() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomPlan,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteCustomPlan,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i2.Either<_i5.Failure, bool> getIsParentMode() => (super.noSuchMethod(
        Invocation.method(
          #getIsParentMode,
          [],
        ),
        returnValue: _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #getIsParentMode,
            [],
          ),
        ),
      ) as _i2.Either<_i5.Failure, bool>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setIsParentMode(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIsParentMode,
          [value],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #setIsParentMode,
            [value],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resyncProductionDataToCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #resyncProductionDataToCloud,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resyncProductionDataToCloud,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> pullProductionDataFromCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #pullProductionDataFromCloud,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #pullProductionDataFromCloud,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> pushCertificatesToCloud(
          List<_i8.CertificateAward>? certificates) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushCertificatesToCloud,
          [certificates],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #pushCertificatesToCloud,
            [certificates],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> revokeGuardianLink(
          String? counterpartUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeGuardianLink,
          [counterpartUserId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #revokeGuardianLink,
            [counterpartUserId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeChild(String? childUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChild,
          [childUserId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeChild,
            [childUserId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
