// Mocks generated by Mockito 5.4.4 from annotations
// in talia_quran/test/features/memorization_plus/presentation/cubits/kids_journey_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talia_quran/core/error/app_failure.dart' as _i5;
import 'package:talia_quran/features/memorization_plus/domain/entities/memorization_entities.dart'
    as _i6;
import 'package:talia_quran/features/memorization_plus/domain/usecases/memorization_plus_usecases.dart'
    as _i3;
import 'package:talia_quran/features/quran/domain/entities/quran_entities.dart'
    as _i8;
import 'package:talia_quran/features/quran/domain/repositories/quran_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetKidsJourneyUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKidsJourneyUsecase extends _i1.Mock
    implements _i3.GetKidsJourneyUsecase {
  MockGetKidsJourneyUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.KidsJourneyStage>>> call(
          _i3.GetKidsJourneyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.KidsJourneyStage>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.KidsJourneyStage>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.KidsJourneyStage>>>);
}

/// A class which mocks [GetKidsProgressUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKidsProgressUsecase extends _i1.Mock
    implements _i3.GetKidsProgressUsecase {
  MockGetKidsProgressUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.KidsProgress>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.KidsProgress>>.value(
                _FakeEither_0<_i5.Failure, _i6.KidsProgress>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.KidsProgress>>);
}

/// A class which mocks [QuranRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranRepository extends _i1.Mock implements _i7.QuranRepository {
  MockQuranRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Surah>>> getSurahs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurahs,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Surah>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Surah>>(
          this,
          Invocation.method(
            #getSurahs,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Surah>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.SurahDetail>> getSurahDetail(
          int? surahId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurahDetail,
          [surahId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.SurahDetail>>.value(
            _FakeEither_0<_i5.Failure, _i8.SurahDetail>(
          this,
          Invocation.method(
            #getSurahDetail,
            [surahId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.SurahDetail>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Surah>>> searchSurahs(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSurahs,
          [query],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Surah>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Surah>>(
          this,
          Invocation.method(
            #searchSurahs,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Surah>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.QuranPageDetail>> getQuranPage(
          int? pageNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuranPage,
          [pageNumber],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.QuranPageDetail>>.value(
                _FakeEither_0<_i5.Failure, _i8.QuranPageDetail>(
          this,
          Invocation.method(
            #getQuranPage,
            [pageNumber],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.QuranPageDetail>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Ayah>>> searchAyahs(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAyahs,
          [query],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Ayah>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Ayah>>(
          this,
          Invocation.method(
            #searchAyahs,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Ayah>>>);
}
